/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Prize;

/**
 *
 * @author guillermo
 */
public class PrizeView extends javax.swing.JPanel {
    
    private Prize prizeModel;
    /**
     * Creates new form PrizeView
     */
    public PrizeView() {
        initComponents();
    }
    /*
        levelsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treasuresText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        levelsText = new javax.swing.JTextArea();
        monsterNameLabel = new javax.swing.JLabel();
        treasuresLabel = new javax.swing.JLabel();
    */
    public void setPrize(Prize p){
        prizeModel = p;
        levelsText.setText(Integer.toString(prizeModel.getLevel()));
        treasuresText.setText(Integer.toString(prizeModel.getTreasures()));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        levelsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treasuresText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        levelsText = new javax.swing.JTextArea();
        prizeLabel = new javax.swing.JLabel();
        treasuresLabel = new javax.swing.JLabel();

        levelsLabel.setText("Levels:");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        treasuresText.setEditable(false);
        treasuresText.setColumns(20);
        treasuresText.setRows(5);
        treasuresText.setFocusable(false);
        jScrollPane1.setViewportView(treasuresText);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        levelsText.setEditable(false);
        levelsText.setColumns(20);
        levelsText.setRows(5);
        levelsText.setFocusable(false);
        jScrollPane2.setViewportView(levelsText);

        prizeLabel.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        prizeLabel.setText("Prize");

        treasuresLabel.setText("Treasures:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(levelsLabel)
                            .addComponent(treasuresLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(treasuresLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(levelsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel levelsLabel;
    private javax.swing.JTextArea levelsText;
    private javax.swing.JLabel prizeLabel;
    private javax.swing.JLabel treasuresLabel;
    private javax.swing.JTextArea treasuresText;
    // End of variables declaration//GEN-END:variables
}
